-- VHDL Entity ip_repo_lib.counter.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 20:24:00 15/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

entity counter is
   port( 
      cnt   : out    std_logic_vector (31 downto 0);
      reset : in     std_logic;
      clk   : in     std_logic
   );

-- Declarations

end counter ;

--
-- VHDL Architecture ip_repo_lib.counter.rtl
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 20:24:00 15/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--

architecture rtl of counter is

   -- Architecture declarations
     signal counter: std_logic_vector(31 downto 0);

begin

   -----------------------------------------------------------------
   process (clk)
   -----------------------------------------------------------------
   begin
      if  rising_edge(clk)  then
         if  reset = '1'  then
            counter <= (others => '0');
         else
            counter <= counter +1;
         end if;
      end if;
   end process;
  cnt<= counter;

end rtl;
