-- VHDL Entity ip_repo_lib.gate_and4in1out.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 02:08:58 11/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity gate_and4in1out is
   port( 
      A : in     std_logic;
      B : in     std_logic;
      C : in     std_logic;
      D : in     std_logic;
      E : out    std_logic
   );

-- Declarations

end gate_and4in1out ;

--
-- VHDL Architecture ip_repo_lib.gate_and4in1out.struct
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 02:08:58 11/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library ip_repo_lib;

architecture struct of gate_and4in1out is

   -- Architecture declarations

   -- Internal signal declarations
   signal C0 : std_logic;
   signal C1 : std_logic;


   -- Component Declarations
   component gate_and
   port (
      A : in     std_logic;
      B : in     std_logic;
      C : out    std_logic
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : gate_and use entity ip_repo_lib.gate_and;
   -- pragma synthesis_on


begin

   -- Instance port mappings.
   U_0 : gate_and
      port map (
         A => A,
         B => B,
         C => C0
      );
   U_1 : gate_and
      port map (
         A => C,
         B => D,
         C => C1
      );
   U_2 : gate_and
      port map (
         A => C0,
         B => C1,
         C => E
      );

end struct;
