-- VHDL Entity ip_repo_lib.power_on_reset.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 23:58:21 09/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;

entity power_on_reset is
   port( 
      clk     : in     std_logic;
      reset_a : in     std_logic;
      reset_s : out    std_logic
   );

-- Declarations

end power_on_reset ;

--
-- VHDL Architecture ip_repo_lib.power_on_reset.rtl
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 23:56:58 09/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--

architecture rtl of power_on_reset is

   -- Architecture declarations
      signal q0,q1,q2: std_logic;

begin

   -----------------------------------------------------------------
   process0_proc : process (clk,reset_a)
   -----------------------------------------------------------------
   begin
      if  reset_a = '0'  then
         q0 <= '0';
         q1 <= '0';
         q2 <= '0';
      elsif  rising_edge(clk) then
         q0 <= reset_a;
         q1 <= q0;
         q2 <= q1;
      end if;
   end process process0_proc;


-- Architecture concurrent statements
reset_s <= not (q0 and q1 and q2);
 

end rtl;
