-- VHDL Entity ip_repo_lib.tb_top_button_debounce.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 02:52:00 11/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity tb_top_button_debounce is
   port( 
      button_deb : out    std_logic
   );

-- Declarations

end tb_top_button_debounce ;

--
-- VHDL Architecture ip_repo_lib.tb_top_button_debounce.struct
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 02:52:00 11/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library ip_repo_lib;

architecture struct of tb_top_button_debounce is

   -- Architecture declarations

   -- Internal signal declarations
   signal clk   : std_logic;
   signal d     : std_logic;
   signal fcw   : std_logic_vector(31 downto 0);
   signal reset : std_logic;


   -- Component Declarations
   component top_debouncer
   port (
      button     : in     std_logic ;
      clk        : in     std_logic ;
      fcw        : in     std_logic_vector (31 downto 0);
      reset      : in     std_logic ;
      button_deb : out    std_logic 
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : top_debouncer use entity ip_repo_lib.top_debouncer;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1 
   process
   begin  
   fcw <= conv_std_logic_vector(1073741824,fcw'length); 
   d <= '0';
   reset <= '0';
   wait for 10ns;
   reset <= '1';
   wait for 70ns;
   reset <= '0';
   wait for 20ns;
   d <= '0';
   wait for 15ns;
   d <= '1';
   wait for 10ns;
   d <= '0';
   wait for 100ns;
   d <= '1';
   wait for 20ns;
   d <= '0';
   wait for 10ns;
   d <= '1';
   wait;
   end process;
   
   --generate clock
   process
   begin
      clk <='0';
      wait for 4ns;
      clk <='1';
      wait for 4ns;
   end process;                     


   -- Instance port mappings.
   U_0 : top_debouncer
      port map (
         button     => d,
         clk        => clk,
         fcw        => fcw,
         reset      => reset,
         button_deb => button_deb
      );

end struct;
