-- VHDL Entity ip_repo_lib.tb_top_buzzer.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 12:05:27 22/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity tb_top_buzzer is
   port( 
      output : out    std_logic_vector (1 downto 0)
   );

-- Declarations

end tb_top_buzzer ;

--
-- VHDL Architecture ip_repo_lib.tb_top_buzzer.struct
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 12:05:27 22/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library ip_repo_lib;

architecture struct of tb_top_buzzer is

   -- Architecture declarations

   -- Internal signal declarations
   signal clk      : std_logic;
   signal sel_freq : std_logic;


   -- Component Declarations
   component top_buzzer
   port (
      clk      : in     std_logic ;
      sel_freq : in     std_logic ;
      output   : out    std_logic_vector (1 downto 0)
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : top_buzzer use entity ip_repo_lib.top_buzzer;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 2 eb2
   -- eb1 1  
   process is
   begin
   sel_freq <= '1';
   clk <= '0';
   wait for 4 ns;
   clk <= '1';
   wait for 4 ns;
   end process;                                      


   -- Instance port mappings.
   U_0 : top_buzzer
      port map (
         clk      => clk,
         sel_freq => sel_freq,
         output   => output
      );

end struct;
