-- VHDL Entity ip_repo_lib.tb_top_counter.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 21:15:48 06/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity tb_top_counter is
-- Declarations

end tb_top_counter ;

--
-- VHDL Architecture ip_repo_lib.tb_top_counter.struct
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 21:15:48 06/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library ip_repo_lib;

architecture struct of tb_top_counter is

   -- Architecture declarations

   -- Internal signal declarations
   signal buttons : std_logic_vector(3 downto 0);
   signal clk     : std_logic;
   signal leds    : std_logic_vector(3 downto 0);
   signal sliders : std_logic_vector(3 downto 0);


   -- Component Declarations
   component top_counter
   port (
      buttons : in     std_logic_vector (3 downto 0);
      clk     : in     std_logic ;
      sliders : in     std_logic_vector (3 downto 0);
      leds    : out    std_logic_vector (3 downto 0)
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : top_counter use entity ip_repo_lib.top_counter;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- generate clock signal
   process
   begin
      clk <='0';
      wait for 5ns;
      clk <='1';
      wait for 5ns;
   end process;
   
   --generate buttons signal
   process
   begin
      buttons <= (others => '0');
      sliders <= (others => '0');
      sliders(0) <= '1';
      wait for 1us;
      sliders(0) <= '0';
      wait for 1us;
      sliders(1) <= '1';
      wait for 1us;
      sliders(2) <= '1';
      wait ;
   end process;


   -- Instance port mappings.
   U_0 : top_counter
      port map (
         buttons => buttons,
         clk     => clk,
         sliders => sliders,
         leds    => leds
      );

end struct;
