-- VHDL Entity ip_repo_lib.top_rotary_decoder.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 21:53:43 12/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity top_rotary_decoder is
   port( 
      A          : in     std_logic;
      B          : in     std_logic;
      clk        : in     std_logic;
      preset     : in     std_logic;
      preset_val : in     std_logic_vector (4 Downto 0);
      led0       : out    std_logic;
      led1       : out    std_logic;
      led2       : out    std_logic;
      led3       : out    std_logic
   );

-- Declarations

end top_rotary_decoder ;

--
-- VHDL Architecture ip_repo_lib.top_rotary_decoder.struct
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 21:54:36 12/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

library ip_repo_lib;

architecture struct of top_rotary_decoder is

   -- Architecture declarations

   -- Internal signal declarations
   signal val : std_logic_vector(4 Downto 0);


   -- Component Declarations
   component rotary_decoder
   port (
      A          : in     std_logic;
      B          : in     std_logic;
      clk        : in     std_logic;
      preset     : in     std_logic;
      preset_val : in     std_logic_vector (4 Downto 0);
      val        : out    std_logic_vector (4 Downto 0)
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : rotary_decoder use entity ip_repo_lib.rotary_decoder;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1 
   led0 <= val(0);    
   led1 <= val(1);                   
   led2 <= val(2);    
   led3 <= val(3);    


   -- Instance port mappings.
   U_0 : rotary_decoder
      port map (
         clk        => clk,
         A          => A,
         B          => B,
         preset     => preset,
         preset_val => preset_val,
         val        => val
      );

end struct;
