-- VHDL Entity ip_repo_lib.top_rotary_decoder.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 02:33:00 13/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity top_rotary_decoder is
   port( 
      A0         : in     std_logic;
      B0         : in     std_logic;
      clk        : in     std_logic;
      preset     : in     std_logic;
      preset_val : in     std_logic_vector (3 Downto 0);
      reset      : in     std_logic;
      led0       : out    std_logic;
      led1       : out    std_logic;
      led2       : out    std_logic;
      led3       : out    std_logic
   );

-- Declarations

end top_rotary_decoder ;

--
-- VHDL Architecture ip_repo_lib.top_rotary_decoder.struct
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 02:33:00 13/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

library ip_repo_lib;

architecture struct of top_rotary_decoder is

   -- Architecture declarations

   -- Internal signal declarations
   signal A      : std_logic;
   signal B      : std_logic;
   signal output : std_logic_vector( 31 downto 0);
   signal val    : std_logic_vector(3 Downto 0);


   -- Component Declarations
   component constant_value
   generic (
      value : integer := 34359;
      nBits : integer := 32
   );
   port (
      output : out    std_logic_vector ( 31 downto 0)
   );
   end component;
   component rotary_decoder
   port (
      A          : in     std_logic;
      B          : in     std_logic;
      clk        : in     std_logic;
      preset     : in     std_logic;
      preset_val : in     std_logic_vector (3 Downto 0);
      val        : out    std_logic_vector (3 Downto 0)
   );
   end component;
   component top_debouncer
   port (
      button     : in     std_logic ;
      clk        : in     std_logic ;
      fcw        : in     std_logic_vector (31 downto 0);
      reset      : in     std_logic ;
      button_deb : out    std_logic 
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : constant_value use entity ip_repo_lib.constant_value;
   for all : rotary_decoder use entity ip_repo_lib.rotary_decoder;
   for all : top_debouncer use entity ip_repo_lib.top_debouncer;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1 
   led0 <= val(0);    
   led1 <= val(1);                   
   led2 <= val(2);    
   led3 <= val(3);    


   -- Instance port mappings.
   U_1 : constant_value
      generic map (
         value => 34359,
         nBits => 32
      )
      port map (
         output => output
      );
   U_0 : rotary_decoder
      port map (
         clk        => clk,
         A          => A,
         B          => B,
         preset     => preset,
         preset_val => preset_val,
         val        => val
      );
   U_2 : top_debouncer
      port map (
         button     => A0,
         clk        => clk,
         fcw        => output,
         reset      => reset,
         button_deb => A
      );
   U_3 : top_debouncer
      port map (
         button     => B0,
         clk        => clk,
         fcw        => output,
         reset      => reset,
         button_deb => B
      );

end struct;
