-- VHDL Entity ip_repo_lib.top_gate_and.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 15:39:40 16/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity top_gate_and is
   port( 
      A : in     std_logic;
      B : in     std_logic;
      C : out    std_logic
   );

-- Declarations

end top_gate_and ;

--
-- VHDL Architecture ip_repo_lib.top_gate_and.struct
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 15:39:40 16/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library ip_repo_lib;

architecture struct of top_gate_and is

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   component gate_and
   port (
      A : in     std_logic;
      B : in     std_logic;
      C : out    std_logic
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : gate_and use entity ip_repo_lib.gate_and;
   -- pragma synthesis_on


begin

   -- Instance port mappings.
   U_0 : gate_and
      port map (
         A => A,
         B => B,
         C => C
      );

end struct;
