-- VHDL Entity ip_repo_lib.top_power_on_reset.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 01:02:17 10/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity top_power_on_reset is
   port( 
      clk     : in     std_logic;
      reset_a : in     std_logic;
      reset_s : out    std_logic
   );

-- Declarations

end top_power_on_reset ;

--
-- VHDL Architecture ip_repo_lib.top_power_on_reset.struct
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 01:02:17 10/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library ip_repo_lib;

architecture struct of top_power_on_reset is

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   component power_on_reset
   port (
      clk     : in     std_logic ;
      reset_a : in     std_logic ;
      reset_s : out    std_logic 
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : power_on_reset use entity ip_repo_lib.power_on_reset;
   -- pragma synthesis_on


begin

   -- Instance port mappings.
   U_0 : power_on_reset
      port map (
         clk     => clk,
         reset_a => reset_a,
         reset_s => reset_s
      );

end struct;
