-- VHDL Entity ip_repo_lib.top_test.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 15:38:59 20/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity top_test is
   port( 
      clk : in     std_logic;
      led : out    std_logic_vector ( 2 downto 0 )
   );

-- Declarations

end top_test ;

--
-- VHDL Architecture ip_repo_lib.top_test.struct
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 15:38:59 20/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

library ip_repo_lib;

architecture struct of top_test is

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   component TEST_RTL
   port (
      clk : in     std_logic ;
      led : out    std_logic_vector ( 2 downto 0 )
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : TEST_RTL use entity ip_repo_lib.TEST_RTL;
   -- pragma synthesis_on


begin

   -- Instance port mappings.
   U_0 : TEST_RTL
      port map (
         clk => clk,
         led => led
      );

end struct;
