-- VHDL Entity ip_repo_lib.top_debouncer.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 02:30:46 11/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity top_debouncer is
   port( 
      button     : in     std_logic;
      clk        : in     std_logic;
      fcw        : in     std_logic_vector (31 downto 0);
      reset      : in     std_logic;
      button_deb : out    std_logic
   );

-- Declarations

end top_debouncer ;

--
-- VHDL Architecture ip_repo_lib.top_debouncer.struct
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 02:30:46 11/12/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library ip_repo_lib;

architecture struct of top_debouncer is

   -- Architecture declarations

   -- Internal signal declarations
   signal stb : std_logic;


   -- Component Declarations
   component top_nco
   port (
      clk   : in     std_logic ;
      fcw   : in     std_logic_vector (31 downto 0);
      reset : in     std_logic ;
      rect  : out    std_logic ;
      stb   : out    std_logic 
   );
   end component;
   component top_shreg_4bit
   port (
      clk : in     std_logic ;
      d   : in     std_logic ;
      en  : in     std_logic ;
      rst : in     std_logic ;
      q_s : out    std_logic 
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : top_nco use entity ip_repo_lib.top_nco;
   for all : top_shreg_4bit use entity ip_repo_lib.top_shreg_4bit;
   -- pragma synthesis_on


begin

   -- Instance port mappings.
   U_4 : top_nco
      port map (
         clk   => clk,
         fcw   => fcw,
         reset => reset,
         rect  => open,
         stb   => stb
      );
   U_0 : top_shreg_4bit
      port map (
         clk => clk,
         d   => button,
         en  => stb,
         rst => reset,
         q_s => button_deb
      );

end struct;
