-- VHDL Entity ip_repo_lib.top_buzzer.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 00:11:50 23/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity top_buzzer is
   port( 
      clk      : in     std_logic;
      en       : in     std_logic;
      sel_freq : in     std_logic;
      leds     : out    std_logic_vector (1 downto 0);
      output   : out    std_logic_vector (1 downto 0)
   );

-- Declarations

end top_buzzer ;

--
-- VHDL Architecture ip_repo_lib.top_buzzer.struct
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 00:11:50 23/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library ip_repo_lib;

architecture struct of top_buzzer is

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   component buzzer
   port (
      clk      : in     std_logic;
      en       : in     std_logic;
      sel_freq : in     std_logic;
      leds     : out    std_logic_vector (1 downto 0);
      output   : out    std_logic_vector (1 downto 0)
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : buzzer use entity ip_repo_lib.buzzer;
   -- pragma synthesis_on


begin

   -- Instance port mappings.
   U_0 : buzzer
      port map (
         en       => en,
         clk      => clk,
         sel_freq => sel_freq,
         output   => output,
         leds     => leds
      );

end struct;
