-- VHDL Entity ip_repo_lib.top_traffic_light.symbol
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 02:33:50 23/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity top_traffic_light is
   port( 
      a        : in     std_logic;
      clk      : in     std_logic;
      en       : in     std_logic;
      en1      : in     std_logic;
      s0       : in     std_logic;
      sel_freq : in     std_logic;
      leds     : out    std_logic_vector (1 downto 0);
      out1     : out    std_logic_vector ( 2 downto 0);
      output   : out    std_logic_vector (1 downto 0)
   );

-- Declarations

end top_traffic_light ;

--
-- VHDL Architecture ip_repo_lib.top_traffic_light.struct
--
-- Created:
--          by - jpnbino.UNKNOWN (DESKTOP-445QT3V)
--          at - 02:33:50 23/11/2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

library ip_repo_lib;

architecture struct of top_traffic_light is

   -- Architecture declarations

   -- Internal signal declarations
   signal led   : std_logic_vector( 2 downto 0 );
   signal leds1 : std_logic_vector( 2 downto 0);


   -- Component Declarations
   component mux2_1
   port (
      in1  : in     std_logic_vector ( 2 downto 0);
      in2  : in     std_logic_vector ( 2 downto 0);
      s0   : in     std_logic;
      out1 : out    std_logic_vector ( 2 downto 0)
   );
   end component;
   component top_buzzer
   port (
      clk      : in     std_logic ;
      en       : in     std_logic ;
      sel_freq : in     std_logic ;
      leds     : out    std_logic_vector (1 downto 0);
      output   : out    std_logic_vector (1 downto 0)
   );
   end component;
   component top_traffic_tester
   port (
      a    : in     std_logic ;
      en   : in     std_logic ;
      leds : out    std_logic_vector ( 2 downto 0)
   );
   end component;
   component traffic_light
   port (
      en  : in     std_logic ;
      clk : in     std_logic ;
      led : out    std_logic_vector ( 2 downto 0 )
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : mux2_1 use entity ip_repo_lib.mux2_1;
   for all : top_buzzer use entity ip_repo_lib.top_buzzer;
   for all : top_traffic_tester use entity ip_repo_lib.top_traffic_tester;
   for all : traffic_light use entity ip_repo_lib.traffic_light;
   -- pragma synthesis_on


begin

   -- Instance port mappings.
   U_4 : mux2_1
      port map (
         s0   => s0,
         in1  => leds1,
         in2  => led,
         out1 => out1
      );
   U_1 : top_buzzer
      port map (
         clk      => clk,
         en       => en,
         sel_freq => sel_freq,
         leds     => leds,
         output   => output
      );
   U_2 : top_traffic_tester
      port map (
         a    => a,
         en   => en1,
         leds => leds1
      );
   U_0 : traffic_light
      port map (
         en  => en1,
         clk => clk,
         led => led
      );

end struct;
